# Generated by Django 5.2.1 on 2025-06-05 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_player_hands_game_table_gameroom_name_profile'),
        ('players', '0002_player_current_room_player_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.AlterField(
            model_name='player',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_players_in_room', to='game.gameroom'),
        ),
    ]
