# Generated by Django 5.2.1 on 2025-06-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('playing', 'Игра идет'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=20)),
                ('trump_suit', models.CharField(blank=True, help_text='Козырная масть (hearts, spades, etc.)', max_length=10, null=True)),
                ('trump_card_revealed', models.JSONField(blank=True, help_text="Карта, которая показывает козырь (если есть 'под колодой')", null=True)),
                ('deck', models.JSONField(default=list, help_text='Список карт в колоде')),
                ('table', models.JSONField(default=list, help_text='Список карт на столе (атака/защита)')),
                ('player_hands', models.JSONField(default=dict, help_text='Словарь {player_id: [карты]} для рук игроков')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние игры',
                'verbose_name_plural': 'Состояния игр',
            },
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название комнаты, если не указано, генерируется.', max_length=100)),
                ('max_players', models.PositiveSmallIntegerField(default=2, help_text='От 2 до 4 игроков')),
                ('bet_amount', models.PositiveIntegerField(default=0, help_text='Ставка для входа в игру')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('playing', 'Игра идет'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Игровая комната',
                'verbose_name_plural': 'Игровые комнаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Находится ли игрок сейчас активно на странице комнаты')),
                ('last_ping', models.DateTimeField(auto_now_add=True, help_text='Время последней активности/пинга')),
            ],
            options={
                'verbose_name': 'Активность игрока',
                'verbose_name_plural': 'Активности игроков',
                'ordering': ['-last_ping'],
            },
        ),
    ]
