# Generated by Django 5.2.1 on 2025-06-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='discard_pile',
        ),
        migrations.RemoveField(
            model_name='game',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='game_type',
            field=models.CharField(choices=[('classic', 'Классический дурак'), ('transfer', 'Переводной дурак')], default='classic', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание игроков'), ('active', 'В процессе'), ('finished', 'Завершена')], default='waiting', max_length=20),
        ),
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['is_active'], name='game_gamero_is_acti_5f73db_idx'),
        ),
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['created_at'], name='game_gamero_created_44052f_idx'),
        ),
    ]
