# Generated by Django 5.2.1 on 2025-06-04 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameroom_last_activity_playeractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gameroom',
            name='game_gamero_is_acti_5f73db_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameroom',
            name='game_gamero_created_44052f_idx',
        ),
        migrations.RenameField(
            model_name='gameroom',
            old_name='created_by',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='current_players',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='playeractivity',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='bet_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание игроков'), ('active', 'Игра идет'), ('finished', 'Завершена')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playeractivity',
            name='connection_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='playeractivity',
            name='last_ping',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
