# Generated by Django 5.2.1 on 2025-06-05 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_gameroom_game_gamero_is_acti_5f73db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='playeractivity',
            options={'verbose_name_plural': 'Player Activities'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AlterField(
            model_name='game',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_instance', to='game.gameroom'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='game_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание игроков'), ('active', 'Игра идет'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playeractivity',
            name='last_ping',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
