# Generated by Django 5.2.1 on 2025-06-05 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_player_hands_game_table_gameroom_name_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Состояние игры', 'verbose_name_plural': 'Состояния игр'},
        ),
        migrations.AlterModelOptions(
            name='gameroom',
            options={'ordering': ['-created_at'], 'verbose_name': 'Игровая комната', 'verbose_name_plural': 'Игровые комнаты'},
        ),
        migrations.AlterModelOptions(
            name='playeractivity',
            options={'ordering': ['-last_ping'], 'verbose_name': 'Активность игрока', 'verbose_name_plural': 'Активности игроков'},
        ),
        migrations.RemoveField(
            model_name='playeractivity',
            name='connection_id',
        ),
        migrations.AddField(
            model_name='game',
            name='trump_card_revealed',
            field=models.JSONField(blank=True, help_text="Карта, которая показывает козырь (если есть 'под колодой')", null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_game_turns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=models.JSONField(default=list, help_text='Список карт в колоде'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_hands',
            field=models.JSONField(default=dict, help_text='Словарь {player_id: [карты]} для рук игроков'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание игроков'), ('playing', 'Игра идет'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='table',
            field=models.JSONField(default=list, help_text='Список карт на столе (атака/защита)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='trump_suit',
            field=models.CharField(blank=True, help_text='Козырная масть (hearts, spades, etc.)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='bet_amount',
            field=models.PositiveIntegerField(default=0, help_text='Ставка для входа в игру'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=2, help_text='От 2 до 4 игроков'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='name',
            field=models.CharField(blank=True, help_text='Название комнаты, если не указано, генерируется.', max_length=100),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='joined_game_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание игроков'), ('playing', 'Игра идет'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_game_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playeractivity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Находится ли игрок сейчас активно на странице комнаты'),
        ),
        migrations.AlterField(
            model_name='playeractivity',
            name='last_ping',
            field=models.DateTimeField(auto_now_add=True, help_text='Время последней активности/пинга'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
